name: Updated

on:
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Create secret file from user and password
      run: |
        echo "BITBUCKET_USER=${{ secrets.BITBUCKET_USER }}" > .env
        echo "BITBUCKET_PASSWORD=${{ secrets.BITBUCKET_PASSWORD }}" >> .env
        echo "GH_PAT=${{ secrets.GH_PAT }}" >> .env

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      env:
        BITBUCKET_PASSWORD: ${{ secrets.BITBUCKET_PASSWORD }}
        GH_PAT: ${{ secrets.GH_PAT }}
      with:
        context: .
        push: true
        tags: splormg/${{ github.event.repository.name }}:latest
        cache-from: type=registry,ref=splormg/${{ github.event.repository.name }}:latest
        cache-to: type=inline
        build-args: |
          BITBUCKET_USER=${{ secrets.BITBUCKET_USER }}
        secrets: |
          id=bitbucket_password,env=BITBUCKET_PASSWORD
          id=gh_pat,env=GH_PAT


    # - name: ETL pipeline
    #   env:
    #     GH_PAT: ${{ secrets.GH_PAT }}
    #     BITBUCKET_USER: ${{ secrets.BITBUCKET_USER }}
    #     BITBUCKET_PASSWORD: ${{ secrets.BITBUCKET_PASSWORD }}
    #   run: docker run  --rm --mount type=bind,source=${PWD},target=/project splormg/${{ github.event.repository.name }} make all
    # - name: Publish data package
    #   run: |-
    #     git config user.name "Automated"
    #     git config user.email "actions@users.noreply.github.com"
    #     make publish
