name: Updated

on:
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      env:
        DOCKER_BUILDKIT: 1
        BITBUCKET_PASSWORD: ${{ secrets.BITBUCKET_PASSWORD }}
        GH_PAT: ${{ secrets.GH_PAT }}
      with:
        context: .
        push: true
        tags: splormg/${{ github.event.repository.name }}:latest
        cache-from: type=registry,ref=splormg/${{ github.event.repository.name }}:latest
        cache-to: type=inline
        build-args: |
          BITBUCKET_USER=${{ secrets.BITBUCKET_USER }}
        secrets: |
          id=bitbucket_password,env=BITBUCKET_PASSWORD
          id=gh_pat,env=GH_PAT
