name: Updated

on:
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Write Bitbucket password secret to file
      run: echo "${{ secrets.BITBUCKET_PASSWORD }}" > bitbucket_password.txt

    - name: Write GitHub PAT secret to file
      run: echo "${{ secrets.GH_PAT }}" > gh_pat.txt

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      env:
        DOCKER_BUILDKIT: 1
      with:
        context: .
        push: true
        tags: splormg/${{ github.event.repository.name }}:latest
        cache-from: type=registry,ref=splormg/${{ github.event.repository.name }}:latest
        cache-to: type=inline
        build-args: |
          BITBUCKET_USER=${{ secrets.BITBUCKET_USER }}
        secrets: |
          id=bitbucket_password,src=bitbucket_password.txt
          id=gh_pat,src=gh_pat.txt

    - name: Remove temporary secret files
      run: rm bitbucket_password.txt gh_pat.txt
