name: Updated

on:
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: splormg/${{ github.event.repository.name }}:latest
        cache-from: type=registry,ref=splormg/${{ github.event.repository.name }}:latest
        cache-to: type=inline|
        build-args: |
          BITBUCKET_USER=${{ secrets.BITBUCKET_USER }}
          BITBUCKET_PASSWORD=${{ secrets.BITBUCKET_PASSWORD }}
          GH_PAT=${{ secrets.GH_PAT }}
    - name: ETL pipeline
      env: 
        GH_PAT: ${{ secrets.GH_PAT }}
        BITBUCKET_USER: ${{ secrets.BITBUCKET_USER }}
        BITBUCKET_PASSWORD: ${{
      run: docker run -e BITBUCKET_USER=$BITBUCKET_USER -e BITBUCKET_PASSWORD=$BITBUCKET_PASSWORD -e GITHUB_PAT=$GH_PAT --rm --mount type=bind,source=${PWD},target=/project splormg/${{ github secrets.BITBUCKET_PASSWORD }}.event.repository.name }} make all
    

  
